import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import RtkProvider from "@/RTK/Provider";
import CopyRightFooter from "@/components/CopyRightFooter/CopyRightFooter";
import TopBar from "@/components/home/top-bar/TopBar";
import { Background } from "@/pages/BookDeatails/BookDetails.style";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">

            <body >
                <RtkProvider>
              
                   <Background>
                    {children}
                   {/*<CopyRightFooter /> */} 
                    </Background>
                </RtkProvider>
               
            </body>
        </html>
    );
}
