import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import RtkProvider from "@/RTK/Provider";
import CopyRightFooter from "@/components/CopyRightFooter/CopyRightFooter";
import TopBar from "@/components/home/top-bar/TopBar";
import { Background } from "@/pages/BookDeatails/BookDetails.style";
import { ThemeProvider } from "@mui/material";
import { theme } from "@/theme/muiTheme";
import { ThemeProvider as JoyProvider } from "@mui/joy";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        
        <html lang="en">

            <body >
            <ThemeProvider theme={theme}>

                <RtkProvider>
                    <Background>
                    <TopBar />
                    {children}
                    <CopyRightFooter />
                    </Background>
                </RtkProvider>
                </ThemeProvider>


               
            </body>
        </html>
    );
}
