export const endpoints = {
    SIGNIN_URL: 'auth/singin',
    SIGNUP_URL: 'auth/signup',
    RESET_PASSWORD_URL: 'auth/reset-password',
    FORGET_PASSWORD_URL: '/auth/forget-password',
    REFRESH_TOKEN_URL: '/auth/refresh',
    POST_METHOD: 'POST',
    PUT_METHOD: 'PUT',
    GET_METHOD : 'GET',
    SIGNUP_VUE_URL: '/auth/signup',
    SIGNIN_VUE_URL: '/auth/login',
    HOME_VUE_URL : '/home',
    PROFILE_VUE_URL : '/profile',
    ADD_BOOK_VUE_URL : 'book/add',
    WISH_LIST_VUE_URL : '/wishlist',
    EDIT_PROFILE_VUE_URL : '/profile/edit',
    BOOK_DETAILS_VUE_URL_START_WITH : '/book/',
    FORGET_PASSWORD_VUE_URL: '/auth/forget-password',
    BOOK_URL : '/books',
    ADD_WISHLIST_URL : '/wishlist',
    ITEM_PER_PAGE_FILTER : '/books?itemPerPage=',
    PAGE_FILTER : '&page=',
    KEY_WORD_FILTER: '&keyword=',
    BOOK_SEARCH_TITLE: '/books/search/title',
    GET_BOOK_BY_USERID_URL : 'books/get/userId?userId=',
    ADMIN_TOTAL_BOOK_COUNT_URL : 'admin-statistics/get-total-books-count',
    ADMIN_BOOKS_ADDED_THIS_WEEK_URL : 'admin-statistics/get-books-added-this-week',
    ADMIN_COMMENTS_COUNT_URL : 'admin-statistics/get-comments-count',
    ADMIN_COMMENTS_ADDED_THIS_WEEK_COUNT_URL : 'admin-statistics/get-comments-added-this-week-count',
    ADMIN_BOOK_COUNT_BY_MONTH_URL : 'admin-statistics/get-books-count-by-month',
    ADMIN_COMMENTS_COUNTS_BY_SENTIMENTS_URL : 'admin-statistics/get-comments-counts-by-sentiments',
    ADMIN_BOOKS_GROUPED_BY_GENRE_URL : 'admin-statistics/get-books-grouped-by-genre',
    RECOMMENDATION_URL : 'recommendation',
    DELETE_METHOD : 'DELETE',
    PATCH_METHOD : 'PATCH',
    ESSAY_URL : 'essay',
    GET_UNREVIEWED_ESSAY_URL : 'essay/unreviewed-essays',
    GET_USER_ESSAY_URL : 'essay/user-essay'

}